import { formatDate } from "@/utils/format-data";

export const MESSAGE_LIST = [
  {
    owner: "bot",
    message:
      "Hello! I'm a chatbot. How can I help you today? Please let me know if you have any questions.",
    htmlContent: "",
    sendTime: formatDate(new Date(), "hh:mm A"),
    react: null,
  },
];

export const SUGGESTION_MESSAGES = [
  {
    message: "타인일정",
    feature: "schedule",
    link: "https://sts.lgcns.com/sch/searcher/index",
  },
  {
    message: "번역",
    feature: "translate",
    link: "https://grp.dt.lgcns.com:9083/trans/reqTrans.do",
  },
  { message: "SMS", feature: "message", link: null },
  { message: "도움말", feature: "message", link: null },
  { message: "내 일정", feature: "message", link: null },
  { message: "날씨", feature: "message", link: null },
  { message: "내 알림", feature: "message", link: null },
  { message: "오늘의메뉴", feature: "message", link: null },
  { message: "Price Plan", feature: "P", link: null },
  { message: "Add On", feature: "A", link: null },
];

export const LIST_OFFER = {
  queryText: "netflix price plan",
  fulfillmentText: "This is the list of netflix price plan.",
  resultList: {
    targetRow: 1,
    orderBy: "",
    defaultRowSize: 0,
    rowSize: 10,
    pageSize: 1,
    rows: 1,
    totalRows: 1,
    currentPage: 1,
    customRowSize: [10, 20, 50],
    list: [
      {
        columnMeta: null,
        targetRow: 1,
        orderBy: "",
        defaultRowSize: 0,
        uuid: "edce4ee0-3d6d-4766-8baa-ef89ee1b60cc",
        code: "PPMS00069",
        name: "5G Netflix Partnership Plan",
        type: "PP",
        basf: "68000.00",
        prodKdCd: null,
        prodKdDetlCd: null,
        prodDivsCd: null,
        prodDetlCd: null,
        spclDtSetCd: null,
        prodRelDivsCd: null,
        smsNotiYn: null,
        exprSmsSndYn: null,
        smsSndMsgFormId: null,
        exprSmsSndMsgFormId: null,
        bndlSbgnPsblYn: null,
        casLinkYn: null,
        entrMmddAplyKdCd: null,
        expyMmddAplyKdCd: null,
        prodKndDivsCd: null,
        tretChgPsblYn: null,
        iptvKdCd: null,
        prodGrdCd: null,
        prodValdStrtDtm: null,
        prodValdEndDtm: null,
        startDate: "2022-08-08 00:00:00",
        endDate: null,
        custInpcProdNm: null,
        maxPsblEntrCnt: null,
        minmPsblEntrCnt: null,
        custKdCd: null,
        prodAgeDivsCd: null,
        duplRegPsblYn: null,
        expyImpsbTermDays: null,
        rjnImpsbTermDays: null,
        entrFeeYn: null,
        susProdEntrPsblYn: null,
        rsvPsblYn: null,
        ythPpEntrPsblYn: null,
        lawcAgntAgrYn: null,
        prodUseTermMmct: null,
        prodAplyCyclCd: null,
        useTermAplyDivsCd: null,
        mbspDcntRqstPsblYn: null,
        aexpCyvl: null,
        rjnPsblTmsc: null,
        aexpYn: null,
        aexpProdAplyCyclCd: null,
        commSkilDivsCd: null,
        rgstUsr: null,
        rgstDtm: null,
        updUsr: null,
        updDtm: null,
        marketName: "MVNO #1",
        customRowSize: [10, 20, 50],
        rowSize: 10,
        pageSize: 10,
      },
      {
        columnMeta: null,
        targetRow: 1,
        orderBy: "",
        defaultRowSize: 0,
        uuid: "16f739af-2d99-4b9b-bd36-d7072d2c68db",
        code: "PPMS00026",
        name: "Lte Data Security 55",
        type: "PP",
        basf: "68000.00",
        prodKdCd: null,
        prodKdDetlCd: null,
        prodDivsCd: null,
        prodDetlCd: null,
        spclDtSetCd: null,
        prodRelDivsCd: null,
        smsNotiYn: null,
        exprSmsSndYn: null,
        smsSndMsgFormId: null,
        exprSmsSndMsgFormId: null,
        bndlSbgnPsblYn: null,
        casLinkYn: null,
        entrMmddAplyKdCd: null,
        expyMmddAplyKdCd: null,
        prodKndDivsCd: null,
        tretChgPsblYn: null,
        iptvKdCd: null,
        prodGrdCd: null,
        prodValdStrtDtm: null,
        prodValdEndDtm: null,
        startDate: "2022-08-08 00:00:00",
        endDate: null,
        custInpcProdNm: null,
        maxPsblEntrCnt: null,
        minmPsblEntrCnt: null,
        custKdCd: null,
        prodAgeDivsCd: null,
        duplRegPsblYn: null,
        expyImpsbTermDays: null,
        rjnImpsbTermDays: null,
        entrFeeYn: null,
        susProdEntrPsblYn: null,
        rsvPsblYn: null,
        ythPpEntrPsblYn: null,
        lawcAgntAgrYn: null,
        prodUseTermMmct: null,
        prodAplyCyclCd: null,
        useTermAplyDivsCd: null,
        mbspDcntRqstPsblYn: null,
        aexpCyvl: null,
        rjnPsblTmsc: null,
        aexpYn: null,
        aexpProdAplyCyclCd: null,
        commSkilDivsCd: null,
        rgstUsr: null,
        rgstDtm: null,
        updUsr: null,
        updDtm: null,
        marketName: "MVNO #1",
        customRowSize: [10, 20, 50],
        rowSize: 10,
        pageSize: 10,
      },
      {
        columnMeta: null,
        targetRow: 1,
        orderBy: "",
        defaultRowSize: 0,
        uuid: "1c7f0391-739b-49e6-b347-48635bd6e0ec",
        code: "PPMS00067",
        name: "Youth Premium Plan",
        type: "PP",
        basf: "68000.00",
        prodKdCd: null,
        prodKdDetlCd: null,
        prodDivsCd: null,
        prodDetlCd: null,
        spclDtSetCd: null,
        prodRelDivsCd: null,
        smsNotiYn: null,
        exprSmsSndYn: null,
        smsSndMsgFormId: null,
        exprSmsSndMsgFormId: null,
        bndlSbgnPsblYn: null,
        casLinkYn: null,
        entrMmddAplyKdCd: null,
        expyMmddAplyKdCd: null,
        prodKndDivsCd: null,
        tretChgPsblYn: null,
        iptvKdCd: null,
        prodGrdCd: null,
        prodValdStrtDtm: null,
        prodValdEndDtm: null,
        startDate: "2022-08-08 00:00:00",
        endDate: null,
        custInpcProdNm: null,
        maxPsblEntrCnt: null,
        minmPsblEntrCnt: null,
        custKdCd: null,
        prodAgeDivsCd: null,
        duplRegPsblYn: null,
        expyImpsbTermDays: null,
        rjnImpsbTermDays: null,
        entrFeeYn: null,
        susProdEntrPsblYn: null,
        rsvPsblYn: null,
        ythPpEntrPsblYn: null,
        lawcAgntAgrYn: null,
        prodUseTermMmct: null,
        prodAplyCyclCd: null,
        useTermAplyDivsCd: null,
        mbspDcntRqstPsblYn: null,
        aexpCyvl: null,
        rjnPsblTmsc: null,
        aexpYn: null,
        aexpProdAplyCyclCd: null,
        commSkilDivsCd: null,
        rgstUsr: null,
        rgstDtm: null,
        updUsr: null,
        updDtm: null,
        marketName: "MVNO #1",
        customRowSize: [10, 20, 50],
        rowSize: 10,
        pageSize: 10,
      },
      {
        columnMeta: null,
        targetRow: 1,
        orderBy: "",
        defaultRowSize: 0,
        uuid: "12921c9b-4e08-4bb9-8db6-f39319f4d529",
        code: "DCMS00017",
        name: "Premium Plan Discount",
        type: "DC",
        basf: "68000.00",
        prodKdCd: null,
        prodKdDetlCd: null,
        prodDivsCd: null,
        prodDetlCd: null,
        spclDtSetCd: null,
        prodRelDivsCd: null,
        smsNotiYn: null,
        exprSmsSndYn: null,
        smsSndMsgFormId: null,
        exprSmsSndMsgFormId: null,
        bndlSbgnPsblYn: null,
        casLinkYn: null,
        entrMmddAplyKdCd: null,
        expyMmddAplyKdCd: null,
        prodKndDivsCd: null,
        tretChgPsblYn: null,
        iptvKdCd: null,
        prodGrdCd: null,
        prodValdStrtDtm: null,
        prodValdEndDtm: null,
        startDate: "2022-08-08 00:00:00",
        endDate: null,
        custInpcProdNm: null,
        maxPsblEntrCnt: null,
        minmPsblEntrCnt: null,
        custKdCd: null,
        prodAgeDivsCd: null,
        duplRegPsblYn: null,
        expyImpsbTermDays: null,
        rjnImpsbTermDays: null,
        entrFeeYn: null,
        susProdEntrPsblYn: null,
        rsvPsblYn: null,
        ythPpEntrPsblYn: null,
        lawcAgntAgrYn: null,
        prodUseTermMmct: null,
        prodAplyCyclCd: null,
        useTermAplyDivsCd: null,
        mbspDcntRqstPsblYn: null,
        aexpCyvl: null,
        rjnPsblTmsc: null,
        aexpYn: null,
        aexpProdAplyCyclCd: null,
        commSkilDivsCd: null,
        rgstUsr: null,
        rgstDtm: null,
        updUsr: null,
        updDtm: null,
        marketName: "MVNO #1",
        customRowSize: [10, 20, 50],
        rowSize: 10,
        pageSize: 10,
      },
      {
        columnMeta: null,
        targetRow: 1,
        orderBy: "",
        defaultRowSize: 0,
        uuid: "5d70c0e4-9a3e-4aa5-9f4d-06168be691e1",
        code: "DCMS00035",
        name: "25% Optional Discount",
        type: "DC",
        basf: "68000.00",
        prodKdCd: null,
        prodKdDetlCd: null,
        prodDivsCd: null,
        prodDetlCd: null,
        spclDtSetCd: null,
        prodRelDivsCd: null,
        smsNotiYn: null,
        exprSmsSndYn: null,
        smsSndMsgFormId: null,
        exprSmsSndMsgFormId: null,
        bndlSbgnPsblYn: null,
        casLinkYn: null,
        entrMmddAplyKdCd: null,
        expyMmddAplyKdCd: null,
        prodKndDivsCd: null,
        tretChgPsblYn: null,
        iptvKdCd: null,
        prodGrdCd: null,
        prodValdStrtDtm: null,
        prodValdEndDtm: null,
        startDate: "2022-08-08 00:00:00",
        endDate: null,
        custInpcProdNm: null,
        maxPsblEntrCnt: null,
        minmPsblEntrCnt: null,
        custKdCd: null,
        prodAgeDivsCd: null,
        duplRegPsblYn: null,
        expyImpsbTermDays: null,
        rjnImpsbTermDays: null,
        entrFeeYn: null,
        susProdEntrPsblYn: null,
        rsvPsblYn: null,
        ythPpEntrPsblYn: null,
        lawcAgntAgrYn: null,
        prodUseTermMmct: null,
        prodAplyCyclCd: null,
        useTermAplyDivsCd: null,
        mbspDcntRqstPsblYn: null,
        aexpCyvl: null,
        rjnPsblTmsc: null,
        aexpYn: null,
        aexpProdAplyCyclCd: null,
        commSkilDivsCd: null,
        rgstUsr: null,
        rgstDtm: null,
        updUsr: null,
        updDtm: null,
        marketName: "MVNO #1",
        customRowSize: [10, 20, 50],
        rowSize: 10,
        pageSize: 10,
      },
      {
        columnMeta: null,
        targetRow: 1,
        orderBy: "",
        defaultRowSize: 0,
        uuid: "62311fbe-7d97-4080-b1c7-dda011d07d6e",
        code: "DCMS00018",
        name: "Tving Discount",
        type: "DC",
        basf: "68000.00",
        prodKdCd: null,
        prodKdDetlCd: null,
        prodDivsCd: null,
        prodDetlCd: null,
        spclDtSetCd: null,
        prodRelDivsCd: null,
        smsNotiYn: null,
        exprSmsSndYn: null,
        smsSndMsgFormId: null,
        exprSmsSndMsgFormId: null,
        bndlSbgnPsblYn: null,
        casLinkYn: null,
        entrMmddAplyKdCd: null,
        expyMmddAplyKdCd: null,
        prodKndDivsCd: null,
        tretChgPsblYn: null,
        iptvKdCd: null,
        prodGrdCd: null,
        prodValdStrtDtm: null,
        prodValdEndDtm: null,
        startDate: "2022-08-08 00:00:00",
        endDate: null,
        custInpcProdNm: null,
        maxPsblEntrCnt: null,
        minmPsblEntrCnt: null,
        custKdCd: null,
        prodAgeDivsCd: null,
        duplRegPsblYn: null,
        expyImpsbTermDays: null,
        rjnImpsbTermDays: null,
        entrFeeYn: null,
        susProdEntrPsblYn: null,
        rsvPsblYn: null,
        ythPpEntrPsblYn: null,
        lawcAgntAgrYn: null,
        prodUseTermMmct: null,
        prodAplyCyclCd: null,
        useTermAplyDivsCd: null,
        mbspDcntRqstPsblYn: null,
        aexpCyvl: null,
        rjnPsblTmsc: null,
        aexpYn: null,
        aexpProdAplyCyclCd: null,
        commSkilDivsCd: null,
        rgstUsr: null,
        rgstDtm: null,
        updUsr: null,
        updDtm: null,
        marketName: "MVNO #1",
        customRowSize: [10, 20, 50],
        rowSize: 10,
        pageSize: 10,
      },
      {
        columnMeta: null,
        targetRow: 1,
        orderBy: "",
        defaultRowSize: 0,
        uuid: "06dacbf3-6c39-40b8-b689-36a03ae9cf0a",
        code: "AOMS00056",
        name: "I폰 분실/파손 보험 150",
        type: "AO",
        basf: "68000.00",
        prodKdCd: null,
        prodKdDetlCd: null,
        prodDivsCd: null,
        prodDetlCd: null,
        spclDtSetCd: null,
        prodRelDivsCd: null,
        smsNotiYn: null,
        exprSmsSndYn: null,
        smsSndMsgFormId: null,
        exprSmsSndMsgFormId: null,
        bndlSbgnPsblYn: null,
        casLinkYn: null,
        entrMmddAplyKdCd: null,
        expyMmddAplyKdCd: null,
        prodKndDivsCd: null,
        tretChgPsblYn: null,
        iptvKdCd: null,
        prodGrdCd: null,
        prodValdStrtDtm: null,
        prodValdEndDtm: null,
        startDate: "2022-08-08 00:00:00",
        endDate: null,
        custInpcProdNm: null,
        maxPsblEntrCnt: null,
        minmPsblEntrCnt: null,
        custKdCd: null,
        prodAgeDivsCd: null,
        duplRegPsblYn: null,
        expyImpsbTermDays: null,
        rjnImpsbTermDays: null,
        entrFeeYn: null,
        susProdEntrPsblYn: null,
        rsvPsblYn: null,
        ythPpEntrPsblYn: null,
        lawcAgntAgrYn: null,
        prodUseTermMmct: null,
        prodAplyCyclCd: null,
        useTermAplyDivsCd: null,
        mbspDcntRqstPsblYn: null,
        aexpCyvl: null,
        rjnPsblTmsc: null,
        aexpYn: null,
        aexpProdAplyCyclCd: null,
        commSkilDivsCd: null,
        rgstUsr: null,
        rgstDtm: null,
        updUsr: null,
        updDtm: null,
        marketName: "MVNO #1",
        customRowSize: [10, 20, 50],
        rowSize: 10,
        pageSize: 10,
      },
    ],
  },
};
