export enum MenuItemID {
  DashBoard = "9",
  OfferSearch = "92",
  OfferCreate = "93",
  ComponentSearch = "60",
  ResourceSearch = "68",
  GroupSearch = "71",
  RelationManager = "42",
  RelationSearch = "106",
  MultiEntitySearch = "80",
  LabelSearch = "96",
  GroupDuplicate = "Duplicate",
  OfferDuplicate = "110",
  ImpactAnalysis = "67",
  TreeView = "65",
  CommonCode = "75",
  ResourceCreate = "69",
  ComponentCreate = "61",
  GroupCreate = "72",
  RelationCreate = "107",
  MultiEntityCreate = "81",
  RelationDuplicate = "111",
  MatrixBuilder = "98",
  PublishManager = "109",
  FactorSearch = "97",
  TableStructure = "99",
}
