<template>
  <div
    class="flex flex-column rounded-[16px] p-3 gap-2 cursor-pointer relative zoom-animation"
    :class="[
      active
        ? `!border-[${BORDER_CONFIG.ACTIVE}] border-[2px]`
        : '!border-lighter border-[1px]',
    ]"
    :draggable="draggable"
    @click="handleClick"
    @dragstart="(event) => handleDragStart(event, event.target)"
    @dragend="handleDragEnd"
    @drag="handleDrag"
  >
    <div class="flex justify-between align-center">
      <div
        class="text-[13px] text-base font-medium w-[60%] text-ellipsis"
        :class="[active ? 'text-[#BA1642]' : 'text-base']"
      >
        <CustomTooltip v-if="!isNew" :content="data.matrixCodeName">
          <span
            class="my-[0px] text-truncate !no-underline"
            :class="[active ? 'text-[#BA1642]' : 'text-base']"
            v-html="highlightedName"
          />
        </CustomTooltip>
        <template v-else>
          <input
            v-model="newInputText"
            type="text"
            class="custom-input"
            placeholder="Matrix Name"
            :disabled="disableInput"
            @input="handleUpdate"
          />
        </template>
      </div>
      <div class="text-[13px] text-lighter text-right w-[35%] text-ellipsis">
        {{ isNew ? $t("product_platform.autoGenerated") : data.matrixCode }}
      </div>
    </div>
    <div
      v-if="data?.factorCodes?.length"
      ref="factorCont"
      class="overflow-hidden"
      :class="listChipClass"
    >
      <div ref="factorWrap" class="flex flex-wrap gap-2">
        <div
          v-for="(factor, index) in data.factorCodes"
          :key="index"
          class="factor-item text-[#3A3B3D] !text-[13px] text-ellipsis"
        >
          <CustomTooltip :content="factor" is-inline />
        </div>
      </div>
    </div>
    <div v-if="isNew" class="new-mark"></div>
    <div v-if="isShowDot" class="dot" @click.stop="handleShowAllChip">...</div>
    <div v-if="showChip" class="w-full">
      <button
        class="ml-[auto] w-[28px] h-[28px] rounded-[50%] border border-lighter flex justify-center align-center"
        @click.stop="handleShowAllChip"
      >
        <chevron-up />
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { BORDER_CONFIG } from "@/constants/index";
import { escapeRegExp } from "@/utils/format-data";
const emit = defineEmits(["onClick", "update:matrixCodeName"]);
const props = defineProps({
  data: {
    type: Object,
    default: () => {},
  },
  active: {
    type: Boolean,
    default: false,
  },
  disableInput: {
    type: Boolean,
    default: false,
  },
  isNew: {
    type: Boolean,
    default: false,
  },
  draggable: {
    type: Boolean,
    default: false,
  },
  searchText: {
    type: String,
    default: "",
  },
  onDragStart: {
    type: Function,
    default: () => {},
  },
  onDragEnd: {
    type: Function,
    default: () => {},
  },
});
const factorCont = ref<any>(null);
const factorWrap = ref<any>(null);
const showChip = ref(false);
const isShowDot = ref(false);
const newInputText = ref(props.data.matrixCodeName);
const handleUpdate = (event) => {
  emit("update:matrixCodeName", event.target.value);
};

const listChipClass = computed(() => {
  const widthClass = isShowDot && !showChip.value ? "w-[calc(100%-28px)]" : "";
  const heightClass = !showChip.value ? "max-h-[28px]" : "";
  return [widthClass, heightClass];
});

const highlightedName = computed(() => {
  if (!props.searchText) return props.data.matrixCodeName;
  const escapedSearchText = escapeRegExp(props.searchText);
  // eslint-disable-next-line security/detect-non-literal-regexp
  const regex = new RegExp(`(${escapedSearchText})`, "gi");
  return props.data.matrixCodeName.replace(
    regex,
    '<span class="highlight">$1</span>'
  );
});

const handleClick = () => {
  emit("onClick", props.data);
};

const handleShowAllChip = () => {
  showChip.value = !showChip.value;
};

const updateIsShowDot = () => {
  isShowDot.value =
    factorWrap.value &&
    factorCont.value &&
    !showChip.value &&
    factorWrap.value?.clientHeight > factorCont.value?.clientHeight;
};

const handleDragStart = (event, element) => {
  event.target.classList.remove("zoom-animation");
  const hiddenDragImg = element.cloneNode(true);
  hiddenDragImg.id = "hiddenDragImg";
  hiddenDragImg.style.opacity = "0";
  const dragImg = element.cloneNode(true);
  dragImg.id = "dragImg";
  dragImg.style.position = "absolute";
  dragImg.style.background = "#fff";
  dragImg.style.width = element.clientWidth + "px";
  dragImg.style.zIndex = "1000";
  dragImg.childNodes[0]?.removeChild(dragImg.childNodes[0].childNodes[1]);
  document.body.appendChild(hiddenDragImg);
  document.body.appendChild(dragImg);
  event.dataTransfer?.setDragImage(hiddenDragImg, 0, 0);
  props.onDragStart(event);
};

const handleDragEnd = (event) => {
  event.target.classList.add("zoom-animation");
  const hiddenDragImg = document.getElementById("hiddenDragImg");
  const dragImage = document.getElementById("dragImg");
  props.onDragEnd(event);
  dragImage?.remove();
  hiddenDragImg?.remove();
};

const handleDrag = (event) => {
  const dragImage = document.getElementById("dragImg");
  if (dragImage && event.pageX !== 0 && event.pageY !== 0) {
    dragImage.style.left = `${event.pageX}px`;
    dragImage.style.top = `${event.pageY}px`;
  }
};

onMounted(updateIsShowDot);
onUpdated(updateIsShowDot);
</script>

<style lang="scss" scoped>
.factor-item {
  height: 28px;
  min-width: 40px;
  max-width: 100px;
  border-radius: 999px;
  padding: 5px 12px;
  background: #f0f2f5;
}
.new-mark {
  width: 8px;
  height: 8px;
  position: absolute;
  top: 6px;
  right: 7px;
  background: #ea4f3a;
  border-radius: 999px;
}
:deep() .highlight {
  background-color: yellow;
}
.custom-input {
  width: 100%;
  font-size: 13px;
  &:focus {
    outline-color: transparent;
  }
  &::placeholder {
    color: #bdc1c7;
    font-weight: 400;
  }
}
.dot {
  background: #f0f2f5;
  text-align: center;
  border-radius: 50%;
  width: 28px;
  height: 28px;
  position: absolute;
  bottom: 12px;
  right: 12px;
  cursor: pointer;
}
</style>
