server:
  port: 8080
  servlet:
    context-path: /prod
  shutdown: graceful
  error:
    whitelabel:
      enabled: false
  tomcat:
    allow-trace: false
    error:
      path: /prod/error

spring:
  datasource:
    #    driver-class-name: org.mariadb.jdbc.Driver
    #    url: jdbc:mariadb://dprod.crwaaauu4okx.ap-northeast-2.rds.amazonaws.com:3306/app
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dprodpostgres.crwaaauu4okx.ap-northeast-2.rds.amazonaws.com:5432/app?currentSchema=lguplus
    username: app
    password: ${SPRING_DATASOURCE_PASSWORD}
  cloud:
    aws:
      region:
        static: ap-northeast-2
        bucket-name:  s3-svcp-app-dev
        object-url: https://s3-svcp-app-dev.s3.ap-northeast-2.amazonaws.com/
logging:
  config: classpath:log4j2-tst.xml
mybatis:
  mapper-locations: classpath:sql/postgresql/*.xml
  configuration:
    map-underscore-to-camel-case: true

external:
  api:
    comm: https://lgu.vizier-service.com