package com.lgcns.svcp.prod.ui.prod.dto.offer;

import lombok.Data;

@Data
public class ProdMDto {
	private String prodUuid;
	private String prodCd;
	private String prodNm;
	private String prodKdCd;
	private String prodKdDetlCd;
	private String prodDivsCd;
	private String prodDetlCd;
	private String spclDtSetCd;
	private String prodRelDivsCd;
	private String smsNotiYn;
	private String exprSmsSndYn;
	private String smsSndMsgFormId;
	private String exprSmsSndMsgFormId;
	private String bndlSbgnPsblYn;
	private String casLinkYn;
	private String entrMmddAplyKdCd;
	private String expyMmddAplyKdCd;
	private String prodKndDivsCd;
	private String tretChgPsblYn;
	private String iptvKdCd;
	private String prodGrdCd;
	private String prodValdStrtDtm;
	private String prodValdEndDtm;
	private String saleValdStrtDtm;
	private String saleValdEndDtm;
	private String custInpcProdNm;
	private String maxPsblEntrCnt;
	private String minmPsblEntrCnt;
	private String custKdCd;
	private String prodAgeDivsCd;
	private String duplRegPsblYn;
	private String expyImpsbTermDays;
	private String rjnImpsbTermDays;
	private String entrFeeYn;
	private String susProdEntrPsblYn;
	private String rsvPsblYn;
	private String ythPpEntrPsblYn;
	private String lawcAgntAgrYn;
	private String prodUseTermMmct;
	private String prodAplyCyclCd;
	private String useTermAplyDivsCd;
	private String mbspDcntRqstPsblYn;
	private String aexpCyvl;
	private String rjnPsblTmsc;
	private String aexpYn;
	private String aexpProdAplyCyclCd;
	private String commSkilDivsCd;
	private String rgstUsr;
	private String rgstDtm;
	private String updUsr;
	private String updDtm;
	private String type;
	private String overView;
	private String comment;
}
