import { COLUMN_FIELD_TYPE } from "@/enums/columnTypes";

const MULTI_ENTITY_SCOPE = {
  SINGLE: "S",
  MULTIPLE: "M",
};
const MULTI_ENTITY_DROP_ACTION = {
  ADD: "Add",
  CHANGE: "Change",
};
const MULTI_ENTITY_APPLY_CATEGORY = {
  EDIT: "Edit",
  DUPPLICATE: "Dupplicate",
};
const MULTI_ENTITY_TYPE = {
  LINE_OF_BUSINESS_INFORMATION: "LB",
  RATING_DISCOUNT: "RD",
  DISCOUNT_TARGET: "DT",
};

const MULTI_ENTITY_SUBTYPE = {
  BUSINESS_LINE: "EBL",
  SALE_COMPANY: "ESC",
  USER_TITLE: "ETC00001",
  DISCOUNT_TARGET: "EDT",
};

const MULTI_ENTITY_DROP_TYPE = {
  GROUP: "groupName",
  OFFER: "offerName",
  COMPONENT: "cpntName",
  RESOURCE: "rscName",
};
const MULTI_ENTITY_DROP_ID = {
  GROUP: "groupUuid",
  OFFER: "offerUuid",
  COMPONENT: "cpntUuid",
  RESOURCE: "rscUuid",
};

const INIT_MULTI_ENTITY_CREATE = {
  itemCode: MULTI_ENTITY_TYPE.LINE_OF_BUSINESS_INFORMATION,
  entityCode: null,
  entityName: null,
  entityTypeCode: null,
  validStartDtm: null,
  validEndDtm: null,
  ovwCntn: null,
  additional: [],
  bsnLineTypeCode: null,
  groupUuid: null,
  offerUuid: null,
  cpntUuid: null,
  rscUuid: null,
  chrgTypeCode: null,
  mvnoBsnoYn: null,
};

const MULTI_ENTITY_DETAIL_DATA = {
  [MULTI_ENTITY_SUBTYPE.BUSINESS_LINE]: [
    {
      sortNo: 1,
      key: "itemCode",
      label: "Type",
      fieldTypeCode: COLUMN_FIELD_TYPE.DL,
      value: null,
      valueText: null,
      lov: null,
      isShow: true,
      isRequired: true,
      canInit: false,
      editable: true,
      groupCode: null,
      attrMaxLength: 100,
    },
    {
      sortNo: 2,
      key: "entityTypeCode",
      label: "Sub Type",
      fieldTypeCode: COLUMN_FIELD_TYPE.DL,
      value: null,
      valueText: null,
      lov: null,
      isShow: true,
      isRequired: true,
      canInit: false,
      editable: true,
      groupCode: null,
      attrMaxLength: 100,
    },
    {
      sortNo: 3,
      key: "entityCode",
      label: "product_platform.multiEntityDetailData.bizLineCode",
      fieldTypeCode: COLUMN_FIELD_TYPE.TF,
      value: null,
      valueText: "product_platform.auto_generation",
      lov: null,
      isShow: true,
      isRequired: false,
      canInit: false,
      editable: false,
      groupCode: null,
      attrMaxLength: 10,
    },
    {
      sortNo: 4,
      key: "entityName",
      label: "product_platform.multiEntityDetailData.bizLineName",
      fieldTypeCode: COLUMN_FIELD_TYPE.TF,
      value: null,
      valueText: null,
      lov: null,
      isShow: true,
      isRequired: true,
      canInit: false,
      editable: true,
      groupCode: null,
      attrMaxLength: 100,
    },
    {
      sortNo: 5,
      key: "bsnLineTypeCode",
      label: "product_platform.multiEntityDetailData.bizLineTypeCode",
      fieldTypeCode: COLUMN_FIELD_TYPE.DL,
      value: null,
      valueText: null,
      lov: null,
      isShow: true,
      isRequired: true,
      canInit: false,
      editable: true,
      groupCode: "G00047",
      attrMaxLength: null,
    },
    {
      sortNo: 6,
      key: "validStartDtm",
      label: "product_platform.validStartDtm",
      fieldTypeCode: COLUMN_FIELD_TYPE.DP,
      value: null,
      valueText: null,
      lov: null,
      isShow: true,
      isRequired: true,
      canInit: false,
      editable: true,
      groupCode: null,
      attrMaxLength: null,
    },
    {
      sortNo: 7,
      key: "validEndDtm",
      label: "product_platform.validEndDtm",
      fieldTypeCode: COLUMN_FIELD_TYPE.DP,
      value: null,
      valueText: null,
      lov: null,
      isShow: true,
      isRequired: false,
      canInit: false,
      editable: true,
      groupCode: null,
      attrMaxLength: null,
    },
  ],
  [MULTI_ENTITY_SUBTYPE.DISCOUNT_TARGET]: [
    {
      sortNo: 1,
      key: "itemCode",
      label: "Type",
      fieldTypeCode: COLUMN_FIELD_TYPE.DL,
      value: null,
      valueText: null,
      lov: null,
      isShow: true,
      isRequired: true,
      canInit: false,
      editable: true,
      groupCode: null,
      attrMaxLength: 100,
    },
    {
      sortNo: 2,
      key: "entityTypeCode",
      label: "Sub Type",
      fieldTypeCode: COLUMN_FIELD_TYPE.DL,
      value: null,
      valueText: null,
      lov: null,
      isShow: true,
      isRequired: true,
      canInit: false,
      editable: true,
      groupCode: null,
      attrMaxLength: 100,
    },
    {
      sortNo: 3,
      key: "entityCode",
      label: "product_platform.multiEntityDetailData.discTargetCode",
      fieldTypeCode: COLUMN_FIELD_TYPE.TF,
      value: null,
      valueText: "product_platform.auto_generation",
      lov: null,
      isShow: true,
      isRequired: false,
      canInit: false,
      editable: false,
      groupCode: null,
      attrMaxLength: 10,
    },
    {
      sortNo: 4,
      key: "entityName",
      label: "product_platform.multiEntityDetailData.discTargetName",
      fieldTypeCode: COLUMN_FIELD_TYPE.TF,
      value: null,
      valueText: null,
      lov: null,
      isShow: true,
      isRequired: true,
      canInit: false,
      editable: true,
      groupCode: null,
      attrMaxLength: 100,
    },

    {
      sortNo: 5,
      key: "groupName",
      label: "product_platform.multiEntityDetailData.groupName",
      fieldTypeCode: COLUMN_FIELD_TYPE.SRCH,
      value: null,
      valueText: null,
      lov: null,
      isShow: true,
      isRequired: false,
      canInit: false,
      editable: true,
      groupCode: "G",
      attrMaxLength: null,
    },
    {
      sortNo: 6,
      key: "offerName",
      label: "product_platform.multiEntityDetailData.offerName",
      fieldTypeCode: COLUMN_FIELD_TYPE.SRCH,
      value: null,
      valueText: null,
      lov: null,
      isShow: true,
      isRequired: false,
      canInit: false,
      editable: true,
      groupCode: "O",
      attrMaxLength: null,
    },
    {
      sortNo: 7,
      key: "cpntName",
      label: "product_platform.multiEntityDetailData.componentName",
      fieldTypeCode: COLUMN_FIELD_TYPE.SRCH,
      value: null,
      valueText: null,
      lov: null,
      isShow: true,
      isRequired: false,
      canInit: false,
      editable: true,
      groupCode: "C",
      attrMaxLength: null,
    },
    {
      sortNo: 8,
      key: "rscName",
      label: "product_platform.multiEntityDetailData.resourceName",
      fieldTypeCode: COLUMN_FIELD_TYPE.SRCH,
      value: null,
      valueText: null,
      lov: null,
      isShow: true,
      isRequired: false,
      canInit: false,
      editable: true,
      groupCode: "R",
      attrMaxLength: null,
    },
    {
      sortNo: 9,
      key: "chrgTypeCode",
      label: "product_platform.multiEntityDetailData.chrgTypeCode",
      fieldTypeCode: COLUMN_FIELD_TYPE.DL,
      value: null,
      valueText: null,
      lov: null,
      isShow: true,
      isRequired: true,
      canInit: false,
      editable: true,
      groupCode: "G00048",
      attrMaxLength: null,
    },
    {
      sortNo: 10,
      key: "validStartDtm",
      label: "product_platform.validStartDtm",
      fieldTypeCode: COLUMN_FIELD_TYPE.DP,
      value: null,
      valueText: null,
      lov: null,
      isShow: true,
      isRequired: true,
      canInit: false,
      editable: true,
      groupCode: null,
      attrMaxLength: null,
    },
    {
      sortNo: 11,
      key: "validEndDtm",
      label: "product_platform.validEndDtm",
      fieldTypeCode: COLUMN_FIELD_TYPE.DP,
      value: null,
      valueText: null,
      lov: null,
      isShow: true,
      isRequired: false,
      canInit: false,
      editable: true,
      groupCode: null,
      attrMaxLength: null,
    },
  ],
  [MULTI_ENTITY_SUBTYPE.SALE_COMPANY]: [
    {
      sortNo: 1,
      key: "itemCode",
      label: "Type",
      fieldTypeCode: COLUMN_FIELD_TYPE.DL,
      value: null,
      valueText: null,
      lov: null,
      isShow: true,
      isRequired: true,
      canInit: false,
      editable: true,
      groupCode: null,
      attrMaxLength: 100,
    },
    {
      sortNo: 2,
      key: "entityTypeCode",
      label: "Sub Type",
      fieldTypeCode: COLUMN_FIELD_TYPE.DL,
      value: null,
      valueText: null,
      lov: null,
      isShow: true,
      isRequired: true,
      canInit: false,
      editable: true,
      groupCode: null,
      attrMaxLength: 100,
    },
    {
      sortNo: 3,
      key: "entityCode",
      label: "product_platform.multiEntityDetailData.saleCorpCode",
      fieldTypeCode: COLUMN_FIELD_TYPE.TF,
      value: null,
      valueText: "product_platform.auto_generation",
      lov: null,
      isShow: true,
      isRequired: false,
      canInit: false,
      editable: false,
      groupCode: null,
      attrMaxLength: 10,
    },
    {
      sortNo: 4,
      key: "entityName",
      label: "product_platform.multiEntityDetailData.saleCorpName",
      fieldTypeCode: COLUMN_FIELD_TYPE.TF,
      value: null,
      valueText: null,
      lov: null,
      isShow: true,
      isRequired: true,
      canInit: false,
      editable: true,
      groupCode: null,
      attrMaxLength: 100,
    },
    {
      sortNo: 5,
      key: "mvnoBsnoYn",
      label: "product_platform.multiEntityDetailData.mvnoBsnoYn",
      fieldTypeCode: COLUMN_FIELD_TYPE.DL,
      value: null,
      valueText: null,
      lov: null,
      isShow: true,
      isRequired: true,
      canInit: false,
      editable: true,
      groupCode: "G00008",
      attrMaxLength: null,
    },
    {
      sortNo: 6,
      key: "validStartDtm",
      label: "product_platform.validStartDtm",
      fieldTypeCode: COLUMN_FIELD_TYPE.DP,
      value: null,
      valueText: null,
      lov: null,
      isShow: true,
      isRequired: true,
      canInit: false,
      editable: true,
      groupCode: null,
      attrMaxLength: null,
    },
    {
      sortNo: 7,
      key: "validEndDtm",
      label: "product_platform.validEndDtm",
      fieldTypeCode: COLUMN_FIELD_TYPE.DP,
      value: null,
      valueText: null,
      lov: null,
      isShow: true,
      isRequired: false,
      canInit: false,
      editable: true,
      groupCode: null,
      attrMaxLength: null,
    },
  ],
};

const MULTI_ENTITY_DETAIL_USER_TITLE = [
  {
    sortNo: 1,
    key: "itemCode",
    label: "Type",
    fieldTypeCode: COLUMN_FIELD_TYPE.DL,
    value: null,
    valueText: null,
    lov: null,
    isShow: true,
    isRequired: true,
    canInit: false,
    editable: true,
    groupCode: null,
    attrMaxLength: 100,
  },
  {
    sortNo: 2,
    key: "entityTypeCode",
    label: "Sub Type",
    fieldTypeCode: COLUMN_FIELD_TYPE.DL,
    value: null,
    valueText: null,
    lov: null,
    isShow: true,
    isRequired: true,
    canInit: false,
    editable: true,
    groupCode: null,
    attrMaxLength: 100,
  },
  {
    sortNo: 3,
    key: "entityCode",
    label: "product_platform.multiEntityDetailData.code",
    fieldTypeCode: COLUMN_FIELD_TYPE.TF,
    value: null,
    valueText: "product_platform.auto_generation",
    lov: null,
    isShow: true,
    isRequired: false,
    canInit: false,
    editable: false,
    groupCode: null,
    attrMaxLength: 10,
  },
  {
    sortNo: 4,
    key: "entityName",
    label: "product_platform.multiEntityDetailData.name",
    fieldTypeCode: COLUMN_FIELD_TYPE.TF,
    value: null,
    valueText: null,
    lov: null,
    isShow: true,
    isRequired: true,
    canInit: false,
    editable: true,
    groupCode: null,
    attrMaxLength: 100,
  },
  {
    sortNo: 5,
    key: "validStartDtm",
    label: "product_platform.validStartDtm",
    fieldTypeCode: COLUMN_FIELD_TYPE.DP,
    value: null,
    valueText: null,
    lov: null,
    isShow: true,
    isRequired: true,
    canInit: false,
    editable: true,
    groupCode: null,
    attrMaxLength: null,
  },
  {
    sortNo: 6,
    key: "validEndDtm",
    label: "product_platform.validEndDtm",
    fieldTypeCode: COLUMN_FIELD_TYPE.DP,
    value: null,
    valueText: null,
    lov: null,
    isShow: true,
    isRequired: false,
    canInit: false,
    editable: true,
    groupCode: null,
    attrMaxLength: null,
  },
];

const MULTI_ENTITY_DETAIL_DATA_GRID = {
  [MULTI_ENTITY_SUBTYPE.BUSINESS_LINE]: [
    {
      sortNo: "1",
      colName: "item_code",
      labelId: "itemCode",
      fieldTypeCode: COLUMN_FIELD_TYPE.DL,
      attrVal: null,
      requiredYn: "Y",
      editYn: "N",
      useYn: null,
      groupCode: null,
      attrMaxLength: 100,
    },
    {
      sortNo: "2",
      colName: "entity_type_code",
      labelId: "entityTypeCode",
      fieldTypeCode: COLUMN_FIELD_TYPE.DL,
      attrVal: null,
      requiredYn: "Y",
      editYn: "N",
      useYn: null,
      groupCode: null,
      attrMaxLength: 100,
    },
    {
      sortNo: "3",
      colName: "entity_code",
      labelId: "entityCode",
      fieldTypeCode: COLUMN_FIELD_TYPE.TF,
      attrVal: "product_platform.auto_generation",
      requiredYn: "N",
      editYn: "N",
      useYn: null,
      groupCode: null,
      attrMaxLength: 10,
    },
    {
      sortNo: "4",
      colName: "entity_name",
      labelId: "entityName",
      fieldTypeCode: COLUMN_FIELD_TYPE.TF,
      attrVal: null,
      requiredYn: "Y",
      editYn: "N",
      useYn: null,
      groupCode: null,
      attrMaxLength: 100,
    },
    {
      sortNo: "5",
      colName: "bsn_line_type_code",
      labelId: "bsnLineTypeCode",
      fieldTypeCode: COLUMN_FIELD_TYPE.DL,
      attrVal: null,
      requiredYn: "Y",
      editYn: "N",
      useYn: null,
      groupCode: "G00047",
      attrMaxLength: null,
    },

    {
      sortNo: "6",
      colName: "valid_start_dtm",
      labelId: "validStartDtm",
      fieldTypeCode: COLUMN_FIELD_TYPE.DP,
      attrVal: null,
      requiredYn: "Y",
      editYn: "N",
      useYn: null,
      groupCode: null,
      attrMaxLength: null,
    },
    {
      sortNo: "7",
      colName: "valid_end_dtm",
      labelId: "validEndDtm",
      fieldTypeCode: COLUMN_FIELD_TYPE.DP,
      attrVal: null,
      requiredYn: "N",
      editYn: "N",
      useYn: null,
      groupCode: null,
      attrMaxLength: null,
    },
  ],
  [MULTI_ENTITY_SUBTYPE.DISCOUNT_TARGET]: [
    {
      sortNo: "1",
      colName: "item_code",
      labelId: "itemCode",
      fieldTypeCode: COLUMN_FIELD_TYPE.DL,
      attrVal: null,
      requiredYn: "Y",
      editYn: "N",
      useYn: null,
      groupCode: null,
      attrMaxLength: 100,
    },
    {
      sortNo: "2",
      colName: "entity_type_code",
      labelId: "entityTypeCode",
      fieldTypeCode: COLUMN_FIELD_TYPE.DL,
      attrVal: null,
      requiredYn: "Y",
      editYn: "N",
      useYn: null,
      groupCode: null,
      attrMaxLength: 100,
    },
    {
      sortNo: "3",
      colName: "entity_code",
      labelId: "entityCode",
      fieldTypeCode: COLUMN_FIELD_TYPE.TF,
      attrVal: null,
      requiredYn: "N",
      editYn: "N",
      useYn: null,
      groupCode: null,
      attrMaxLength: 10,
    },
    {
      sortNo: "4",
      colName: "entity_name",
      labelId: "entityName",
      fieldTypeCode: COLUMN_FIELD_TYPE.TF,
      attrVal: null,
      requiredYn: "Y",
      editYn: "N",
      useYn: null,
      groupCode: null,
      attrMaxLength: 100,
    },
    {
      sortNo: "5",
      colName: "group_name",
      labelId: "groupName",
      fieldTypeCode: COLUMN_FIELD_TYPE.SRCH,
      attrVal: null,
      requiredYn: "N",
      editYn: "N",
      useYn: null,
      groupCode: "G",
      attrMaxLength: null,
    },
    {
      sortNo: "6",
      colName: "offer_name",
      labelId: "offerName",
      fieldTypeCode: COLUMN_FIELD_TYPE.SRCH,
      attrVal: null,
      requiredYn: "N",
      editYn: "N",
      useYn: null,
      groupCode: "O",
      attrMaxLength: null,
    },
    {
      sortNo: "7",
      colName: "cpnt_name",
      labelId: "cpntName",
      fieldTypeCode: COLUMN_FIELD_TYPE.SRCH,
      attrVal: null,
      requiredYn: "N",
      editYn: "N",
      useYn: null,
      groupCode: "C",
      attrMaxLength: null,
    },
    {
      sortNo: "8",
      colName: "rsc_name",
      labelId: "rscName",
      fieldTypeCode: COLUMN_FIELD_TYPE.SRCH,
      attrVal: null,
      requiredYn: "N",
      editYn: "N",
      useYn: null,
      groupCode: "R",
      attrMaxLength: null,
    },
    {
      sortNo: "9",
      colName: "chrg_type_code",
      labelId: "chrgTypeCode",
      fieldTypeCode: COLUMN_FIELD_TYPE.DL,
      attrVal: null,
      requiredYn: "Y",
      editYn: "N",
      useYn: null,
      groupCode: "G00048",
      attrMaxLength: null,
    },
    {
      sortNo: "10",
      colName: "valid_start_dtm",
      labelId: "validStartDtm",
      fieldTypeCode: COLUMN_FIELD_TYPE.DP,
      attrVal: null,
      requiredYn: "Y",
      editYn: "N",
      useYn: null,
      groupCode: null,
      attrMaxLength: null,
    },
    {
      sortNo: "11",
      colName: "valid_end_dtm",
      labelId: "validEndDtm",
      fieldTypeCode: COLUMN_FIELD_TYPE.DP,
      attrVal: null,
      requiredYn: "N",
      editYn: "N",
      useYn: null,
      groupCode: null,
      attrMaxLength: null,
    },
  ],
  [MULTI_ENTITY_SUBTYPE.SALE_COMPANY]: [
    {
      sortNo: "1",
      colName: "item_code",
      labelId: "itemCode",
      fieldTypeCode: COLUMN_FIELD_TYPE.DL,
      attrVal: null,
      requiredYn: "Y",
      editYn: "N",
      useYn: null,
      groupCode: null,
      attrMaxLength: 100,
    },
    {
      sortNo: "2",
      colName: "entity_type_code",
      labelId: "entityTypeCode",
      fieldTypeCode: COLUMN_FIELD_TYPE.DL,
      attrVal: null,
      requiredYn: "Y",
      editYn: "N",
      useYn: null,
      groupCode: null,
      attrMaxLength: 100,
    },
    {
      sortNo: "3",
      colName: "entity_code",
      labelId: "entityCode",
      fieldTypeCode: COLUMN_FIELD_TYPE.TF,
      attrVal: "product_platform.auto_generation",
      requiredYn: "N",
      editYn: "N",
      useYn: null,
      groupCode: null,
      attrMaxLength: 10,
    },
    {
      sortNo: "4",
      colName: "entity_name",
      labelId: "entityName",
      fieldTypeCode: COLUMN_FIELD_TYPE.TF,
      attrVal: null,
      requiredYn: "Y",
      editYn: "N",
      useYn: null,
      groupCode: null,
      attrMaxLength: 100,
    },
    {
      sortNo: "5",
      colName: "mvno_bsno_yn",
      labelId: "mvnoBsnoYn",
      fieldTypeCode: COLUMN_FIELD_TYPE.DL,
      attrVal: "product_platform.auto_generation",
      requiredYn: "Y",
      editYn: "N",
      useYn: null,
      groupCode: "G00008",
      attrMaxLength: null,
    },
    {
      sortNo: "6",
      colName: "valid_start_dtm",
      labelId: "validStartDtm",
      fieldTypeCode: COLUMN_FIELD_TYPE.DP,
      attrVal: null,
      requiredYn: "Y",
      editYn: "N",
      useYn: null,
      groupCode: null,
      attrMaxLength: null,
    },
    {
      sortNo: "7",
      colName: "valid_end_dtm",
      labelId: "validEndDtm",
      fieldTypeCode: COLUMN_FIELD_TYPE.DP,
      attrVal: null,
      requiredYn: "N",
      editYn: "N",
      useYn: null,
      groupCode: null,
      attrMaxLength: null,
    },
  ],
};

const MULTI_ENTITY_DETAIL_USER_TITLE_GRID = [
  {
    sortNo: "1",
    colName: "item_code",
    labelId: "itemCode",
    fieldTypeCode: COLUMN_FIELD_TYPE.DL,
    attrVal: null,
    requiredYn: "Y",
    editYn: "Y",
    useYn: null,
    groupCode: null,
    attrMaxLength: 100,
  },
  {
    sortNo: "2",
    colName: "entity_type_code",
    labelId: "entityTypeCode",
    fieldTypeCode: COLUMN_FIELD_TYPE.DL,
    attrVal: null,
    requiredYn: "Y",
    editYn: "Y",
    useYn: null,
    groupCode: null,
    attrMaxLength: 100,
  },
  {
    sortNo: "3",
    colName: "entity_code",
    labelId: "entityCode",
    fieldTypeCode: COLUMN_FIELD_TYPE.TF,
    attrVal: "product_platform.auto_generation",
    requiredYn: "N",
    editYn: "N",
    useYn: null,
    groupCode: null,
    attrMaxLength: 10,
  },
  {
    sortNo: "4",
    colName: "entity_name",
    labelId: "entityName",
    fieldTypeCode: COLUMN_FIELD_TYPE.TF,
    attrVal: null,
    requiredYn: "Y",
    editYn: "Y",
    useYn: null,
    groupCode: null,
    attrMaxLength: 100,
  },
  {
    sortNo: "5",
    colName: "valid_start_dtm",
    labelId: "validStartDtm",
    fieldTypeCode: COLUMN_FIELD_TYPE.DP,
    attrVal: null,
    requiredYn: "Y",
    editYn: "Y",
    useYn: null,
    groupCode: null,
    attrMaxLength: null,
  },
  {
    sortNo: "6",
    colName: "valid_end_dtm",
    labelId: "validEndDtm",
    fieldTypeCode: COLUMN_FIELD_TYPE.DP,
    attrVal: null,
    requiredYn: "N",
    editYn: "Y",
    useYn: null,
    groupCode: null,
    attrMaxLength: null,
  },
];

export {
  MULTI_ENTITY_TYPE,
  MULTI_ENTITY_SUBTYPE,
  MULTI_ENTITY_DETAIL_DATA,
  MULTI_ENTITY_DETAIL_USER_TITLE,
  MULTI_ENTITY_DROP_TYPE,
  INIT_MULTI_ENTITY_CREATE,
  MULTI_ENTITY_DROP_ID,
  MULTI_ENTITY_SCOPE,
  MULTI_ENTITY_APPLY_CATEGORY,
  MULTI_ENTITY_DROP_ACTION,
  MULTI_ENTITY_DETAIL_USER_TITLE_GRID,
  MULTI_ENTITY_DETAIL_DATA_GRID,
};
