apiVersion: v1
kind: Service
metadata:
  name: "service-svcp-sbui"
  namespace: d-svcp-sbui
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: svcp-sbui